version: '3.8'

services:
  db:
    image: postgres:16
    container_name: db
    ports:
      - 5555:5432
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  db:
